version: 0.2

phases: 
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install unit.js
  build:
    commands:
      #build
      - echo Building...
      - npm install
artifacts:
  files:
    "**/*"
